### PR TITLE
PE+LU module implementation

### PR DESCRIPTION
**Pull request by choucl**
- The PE and LU module has been written. And I've done some verification to check they could work properly. Please have a look and see if any modification is need.
- Some new definitions has been added to the `def.v` file.

### CODE REVIEW

**Comment by kkk080808** [comment]
Maybe indentation is needed within the scope of module PE?

**Review by jumha — APPROVED** [review]
Great!

**Comment by choucl** [comment]
@kkk080808 I don't get it. Maybe you can point out the position?

**Comment by jumha** [comment]
OK!

**Pull request merged**
