### PR TITLE
Modify the timing of busy signal

### PR DESCRIPTION
**Pull request by jumha**
I have modified controller.v to match the timing. Please have a look.

### CODE REVIEW

**Review by choucl — APPROVED** [review]
Great, I've also changed the simulation result in the `README.md`

**Review by kkk080808 — APPROVED** [review]

**Comment by choucl** [comment]
@jumha @kkk080808 
I've fixed the controller to meet the newly released testbench.
Also, the image in the `README.md` has been changed for the new simulation result, and also, some typo were fixed.
Please have a look before merging it

**Review by choucl — APPROVED** [review]

**Review by kkk080808 — APPROVED** [review]

**Comment by jumha** [comment]
@choucl @kkk080808 
I add the detail and diagram of our FSM in `README.md`. 
Please have a look, and if there is no problem, I will merge this branch.

**Comment by kkk080808** [comment]
The path to FSM.png is "/home/jumha/FPGA-Set/images/FSM.png", and I did not see "FSM.png" in images.

**Review by choucl — APPROVED** [review]

**Review by kkk080808 — APPROVED** [review]

**Pull request merged**
